[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "Xtrapol8"
dynamic = ["version"]
description = "Xtrapol8"
authors = [
    { name = "Elke De Zitter", email = "elke.de-zitter@ibs.fr" },
    { name = "Nicolas Coquelle" },
    { name = "Paula Oeser" },
    { name = "Thomas Barends" },
    { name = "Jacques Philippe Colletier", email = "jacques-Philippe.colletier@ibs.fr" },
]
readme = "README.md"
license = { text = "MIT" }
keywords = ["Xtrapol8"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.9"
dependencies = [
    "cctbx",
    "chapi",
    "iotbx",
    "libtbx",
    "matplotlib",
    "mmtbx",
    "numpy",
    "pandas",
    "pypubsub",
    "scipy",
    "wxPython",
]

[project.scripts]
"xtrapol8-ddm" = "xtrapol8.ddm:main"
"xtrapol8-difference-map-analysis" = "xtrapol8.differencemap_analysis:main"
"xtrapol8-distance-analysis" = "xtrapol8.distance_analysis:main"
"xtrapol8" = "xtrapol8.Fextr:main"
"xtrapol8-refiner" = "xtrapol8.refiner:main"
"xtrapol8-version" = "xtrapol8.version:main"
"xtrapol8-gui" = "xtrapol8.X8_gui:main"

[project.urls]
Source = "https://github.com/ElkeDeZitter/Xtrapol8"
Issues = "https://github.com/ElkeDeZitter/Xtrapol8/issues"

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "F",  # Pyflakes
    "I",  # isort
    "PL", # Pylint
    "W",  # pycodestyle warnings
]
ignore = [
    "PLR0913", # Too many arguments
    "PLR2004", # Magic constant value
]

[tool.setuptools.dynamic]
version = { attr = "xtrapol8.__version__" }

[tool.setuptools.package-data]
xtrapol8 = ["**/*"]
